@BeyondTodoApi_HostAddress = http://localhost:5209


###

POST {{BeyondTodoApi_HostAddress}}/todos
Content-Type: application/json

{
  "title": "Learn C#",
  "description": "Study C# programming language fundamentals.",
  "category": "Works"
}


